/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppMainLayoutRouteImport } from './routes/_appMainLayout'
import { Route as AppMainLayoutIndexRouteImport } from './routes/_appMainLayout/index'
import { Route as AppMainLayoutTestRouteImport } from './routes/_appMainLayout/test'
import { Route as AppMainLayoutMemoryRouteImport } from './routes/_appMainLayout/memory'
import { Route as AppMainLayoutIdeaRouteImport } from './routes/_appMainLayout/idea'
import { Route as AppMainLayoutArtifactRouteImport } from './routes/_appMainLayout/artifact'

const AppMainLayoutRoute = AppMainLayoutRouteImport.update({
  id: '/_appMainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMainLayoutIndexRoute = AppMainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMainLayoutRoute,
} as any)
const AppMainLayoutTestRoute = AppMainLayoutTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AppMainLayoutRoute,
} as any)
const AppMainLayoutMemoryRoute = AppMainLayoutMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppMainLayoutRoute,
} as any)
const AppMainLayoutIdeaRoute = AppMainLayoutIdeaRouteImport.update({
  id: '/idea',
  path: '/idea',
  getParentRoute: () => AppMainLayoutRoute,
} as any)
const AppMainLayoutArtifactRoute = AppMainLayoutArtifactRouteImport.update({
  id: '/artifact',
  path: '/artifact',
  getParentRoute: () => AppMainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppMainLayoutIndexRoute
  '/artifact': typeof AppMainLayoutArtifactRoute
  '/idea': typeof AppMainLayoutIdeaRoute
  '/memory': typeof AppMainLayoutMemoryRoute
  '/test': typeof AppMainLayoutTestRoute
}
export interface FileRoutesByTo {
  '/artifact': typeof AppMainLayoutArtifactRoute
  '/idea': typeof AppMainLayoutIdeaRoute
  '/memory': typeof AppMainLayoutMemoryRoute
  '/test': typeof AppMainLayoutTestRoute
  '/': typeof AppMainLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appMainLayout': typeof AppMainLayoutRouteWithChildren
  '/_appMainLayout/artifact': typeof AppMainLayoutArtifactRoute
  '/_appMainLayout/idea': typeof AppMainLayoutIdeaRoute
  '/_appMainLayout/memory': typeof AppMainLayoutMemoryRoute
  '/_appMainLayout/test': typeof AppMainLayoutTestRoute
  '/_appMainLayout/': typeof AppMainLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/artifact' | '/idea' | '/memory' | '/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/artifact' | '/idea' | '/memory' | '/test' | '/'
  id:
    | '__root__'
    | '/_appMainLayout'
    | '/_appMainLayout/artifact'
    | '/_appMainLayout/idea'
    | '/_appMainLayout/memory'
    | '/_appMainLayout/test'
    | '/_appMainLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppMainLayoutRoute: typeof AppMainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_appMainLayout': {
      id: '/_appMainLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppMainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appMainLayout/': {
      id: '/_appMainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppMainLayoutIndexRouteImport
      parentRoute: typeof AppMainLayoutRoute
    }
    '/_appMainLayout/test': {
      id: '/_appMainLayout/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AppMainLayoutTestRouteImport
      parentRoute: typeof AppMainLayoutRoute
    }
    '/_appMainLayout/memory': {
      id: '/_appMainLayout/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMainLayoutMemoryRouteImport
      parentRoute: typeof AppMainLayoutRoute
    }
    '/_appMainLayout/idea': {
      id: '/_appMainLayout/idea'
      path: '/idea'
      fullPath: '/idea'
      preLoaderRoute: typeof AppMainLayoutIdeaRouteImport
      parentRoute: typeof AppMainLayoutRoute
    }
    '/_appMainLayout/artifact': {
      id: '/_appMainLayout/artifact'
      path: '/artifact'
      fullPath: '/artifact'
      preLoaderRoute: typeof AppMainLayoutArtifactRouteImport
      parentRoute: typeof AppMainLayoutRoute
    }
  }
}

interface AppMainLayoutRouteChildren {
  AppMainLayoutArtifactRoute: typeof AppMainLayoutArtifactRoute
  AppMainLayoutIdeaRoute: typeof AppMainLayoutIdeaRoute
  AppMainLayoutMemoryRoute: typeof AppMainLayoutMemoryRoute
  AppMainLayoutTestRoute: typeof AppMainLayoutTestRoute
  AppMainLayoutIndexRoute: typeof AppMainLayoutIndexRoute
}

const AppMainLayoutRouteChildren: AppMainLayoutRouteChildren = {
  AppMainLayoutArtifactRoute: AppMainLayoutArtifactRoute,
  AppMainLayoutIdeaRoute: AppMainLayoutIdeaRoute,
  AppMainLayoutMemoryRoute: AppMainLayoutMemoryRoute,
  AppMainLayoutTestRoute: AppMainLayoutTestRoute,
  AppMainLayoutIndexRoute: AppMainLayoutIndexRoute,
}

const AppMainLayoutRouteWithChildren = AppMainLayoutRoute._addFileChildren(
  AppMainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppMainLayoutRoute: AppMainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
