services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      CLOUDY_HOST: 0.0.0.0
      CLOUDY_PORT: 3000
      CLOUDY_UI: "true"

    volumes:
      - ./apps/server/config:/root/.config/cloudy
    extra_hosts:
      - "host.docker.internal:host-gateway"
