import { addCollection } from "@iconify/react";
import type { IconifyJSON } from "@iconify/react";
// Generated by `pnpm --filter web-app generate:file-icons`.
// Contains only the icon-name strings referenced below — keeps the bundle
// tiny (~30 KB) instead of shipping the full 1 MB-gzipped vscode-icons set.
import collection from "./file-icons.generated.json" with { type: "json" };

// Register the curated subset once at module load. Subsequent `<Icon>` renders
// resolve purely from storage, no network/API fallback.
addCollection(collection as IconifyJSON);

/**
 * Map of file extension (lowercase, no dot) → vscode-icons icon name.
 * Keep values in sync with `scripts/extract-file-icons.mjs` (it reads the
 * string literals in this file to decide what to bundle).
 */
export const EXTENSION_TO_ICON: Record<string, string> = {
  // TypeScript / JavaScript family
  ts: "file-type-typescript",
  tsx: "file-type-reactts",
  js: "file-type-js",
  jsx: "file-type-reactjs",
  mjs: "file-type-js",
  cjs: "file-type-js",
  mts: "file-type-typescript",
  cts: "file-type-typescript",
  // Data / config
  json: "file-type-json",
  jsonc: "file-type-json",
  yaml: "file-type-yaml",
  yml: "file-type-yaml",
  toml: "file-type-toml",
  xml: "file-type-xml",
  ini: "file-type-config",
  // Markup / style
  html: "file-type-html",
  htm: "file-type-html",
  css: "file-type-css",
  scss: "file-type-scss",
  sass: "file-type-sass",
  less: "file-type-less",
  vue: "file-type-vue",
  svelte: "file-type-svelte",
  // Docs
  md: "file-type-markdown",
  mdx: "file-type-markdown",
  txt: "file-type-text",
  // Languages
  py: "file-type-python",
  pyw: "file-type-python",
  rb: "file-type-ruby",
  go: "file-type-go",
  rs: "file-type-rust",
  java: "file-type-java",
  kt: "file-type-kotlin",
  kts: "file-type-kotlin",
  swift: "file-type-swift",
  c: "file-type-c",
  h: "file-type-cheader",
  cpp: "file-type-cpp",
  cc: "file-type-cpp",
  cxx: "file-type-cpp",
  hpp: "file-type-cppheader",
  hxx: "file-type-cppheader",
  cs: "file-type-csharp",
  php: "file-type-php",
  sh: "file-type-shell",
  bash: "file-type-shell",
  zsh: "file-type-shell",
  sql: "file-type-sql",
  // Images
  png: "file-type-image",
  jpg: "file-type-image",
  jpeg: "file-type-image",
  gif: "file-type-image",
  bmp: "file-type-image",
  webp: "file-type-image",
  ico: "file-type-image",
  svg: "file-type-svg",
  // Media
  mp4: "file-type-video",
  webm: "file-type-video",
  mov: "file-type-video",
  avi: "file-type-video",
  mkv: "file-type-video",
  mp3: "file-type-audio",
  wav: "file-type-audio",
  ogg: "file-type-audio",
  flac: "file-type-audio",
  // Archives
  zip: "file-type-zip",
  tar: "file-type-zip",
  gz: "file-type-zip",
  rar: "file-type-zip",
  "7z": "file-type-zip",
  // Misc
  pdf: "file-type-pdf2",
  lock: "file-type-text",
  log: "file-type-text",
};

/**
 * Map of full lowercase filename → icon name. Checked before extension lookup
 * so e.g. `package.json` resolves to the npm icon rather than generic json.
 */
export const FILENAME_TO_ICON: Record<string, string> = {
  // Package managers
  "package.json": "file-type-npm",
  "package-lock.json": "file-type-npm",
  "pnpm-lock.yaml": "file-type-pnpm",
  "yarn.lock": "file-type-yarn",
  "bun.lockb": "file-type-bun",
  "bun.lock": "file-type-bun",
  // TS / build
  "tsconfig.json": "file-type-tsconfig",
  "jsconfig.json": "file-type-tsconfig",
  "vite.config.ts": "file-type-vite",
  "vite.config.js": "file-type-vite",
  "vite.config.mts": "file-type-vite",
  "vite.config.mjs": "file-type-vite",
  // Lint / format
  "eslint.config.js": "file-type-eslint",
  "eslint.config.mjs": "file-type-eslint",
  "eslint.config.ts": "file-type-eslint",
  ".eslintrc": "file-type-eslint",
  ".eslintrc.json": "file-type-eslint",
  ".eslintrc.js": "file-type-eslint",
  ".eslintrc.cjs": "file-type-eslint",
  ".prettierrc": "file-type-prettier",
  ".prettierrc.json": "file-type-prettier",
  "prettier.config.js": "file-type-prettier",
  // Container / infra
  dockerfile: "file-type-docker",
  "docker-compose.yml": "file-type-docker",
  "docker-compose.yaml": "file-type-docker",
  makefile: "file-type-config",
  // Git
  ".gitignore": "file-type-git",
  ".gitattributes": "file-type-git",
  ".gitconfig": "file-type-git",
  ".git-blame-ignore-revs": "file-type-git",
  // Env / secrets
  ".env": "file-type-dotenv",
  ".env.local": "file-type-dotenv",
  ".env.production": "file-type-dotenv",
  ".env.development": "file-type-dotenv",
  // Docs / legal
  license: "file-type-license",
  "license.md": "file-type-license",
  copying: "file-type-license",
  authors: "file-type-text",
};

/** Fallback icon when nothing matches (and for unknown extensions). */
export const DEFAULT_FILE_ICON = "default-file";

/**
 * Resolve a vscode-icons icon name for the given `FileNode.name`.
 *
 * Handles dotfiles (`.gitignore`), compound extensions (`.d.ts`), full
 * filenames (`package.json`) and case-insensitivity. Always returns a name
 * that has been registered via `addCollection` above.
 */
export function getFileIconName(name: string): string {
  const lower = name.toLowerCase();

  // Full-filename match wins (package.json, Dockerfile, .gitignore, …).
  if (FILENAME_TO_ICON[lower]) return FILENAME_TO_ICON[lower];

  // Special-case `.d.ts` / `.d.mts` / `.d.cts` before generic extension split,
  // otherwise `foo.d.ts` would match the `ts` entry and lose the "def" variant.
  if (lower.endsWith(".d.ts")) return EXTENSION_TO_ICON["ts"];
  if (lower.endsWith(".d.mts")) return EXTENSION_TO_ICON["mts"];
  if (lower.endsWith(".d.cts")) return EXTENSION_TO_ICON["cts"];

  const ext = lower.split(".").pop() ?? "";
  return EXTENSION_TO_ICON[ext] ?? DEFAULT_FILE_ICON;
}
