/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AppMainLayoutRouteImport } from './routes/_appMainLayout'
import { Route as AppMainLayoutIndexRouteImport } from './routes/_appMainLayout/index'
import { Route as AppMainLayoutDeskRouteImport } from './routes/_appMainLayout/desk'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMainLayoutRoute = AppMainLayoutRouteImport.update({
  id: '/_appMainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMainLayoutIndexRoute = AppMainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMainLayoutRoute,
} as any)
const AppMainLayoutDeskRoute = AppMainLayoutDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => AppMainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppMainLayoutIndexRoute
  '/home': typeof HomeRoute
  '/desk': typeof AppMainLayoutDeskRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/desk': typeof AppMainLayoutDeskRoute
  '/': typeof AppMainLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appMainLayout': typeof AppMainLayoutRouteWithChildren
  '/home': typeof HomeRoute
  '/_appMainLayout/desk': typeof AppMainLayoutDeskRoute
  '/_appMainLayout/': typeof AppMainLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home' | '/desk'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/desk' | '/'
  id:
    | '__root__'
    | '/_appMainLayout'
    | '/home'
    | '/_appMainLayout/desk'
    | '/_appMainLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppMainLayoutRoute: typeof AppMainLayoutRouteWithChildren
  HomeRoute: typeof HomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appMainLayout': {
      id: '/_appMainLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppMainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appMainLayout/': {
      id: '/_appMainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppMainLayoutIndexRouteImport
      parentRoute: typeof AppMainLayoutRoute
    }
    '/_appMainLayout/desk': {
      id: '/_appMainLayout/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof AppMainLayoutDeskRouteImport
      parentRoute: typeof AppMainLayoutRoute
    }
  }
}

interface AppMainLayoutRouteChildren {
  AppMainLayoutDeskRoute: typeof AppMainLayoutDeskRoute
  AppMainLayoutIndexRoute: typeof AppMainLayoutIndexRoute
}

const AppMainLayoutRouteChildren: AppMainLayoutRouteChildren = {
  AppMainLayoutDeskRoute: AppMainLayoutDeskRoute,
  AppMainLayoutIndexRoute: AppMainLayoutIndexRoute,
}

const AppMainLayoutRouteWithChildren = AppMainLayoutRoute._addFileChildren(
  AppMainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppMainLayoutRoute: AppMainLayoutRouteWithChildren,
  HomeRoute: HomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
